### ISSUE TITLE
敵を動かす時間間隔は何秒?

### ISSUE THREAD

**Issue by TateIsuKanna** [eeekcct/katenji#2]

**Comment by eeekcct** [comment]
秒数にではなくプログラムのループの回数で動かしています

**Comment by TateIsuKanna** [comment]
はい，それは分かっていますが，何秒が目標ですか?
あと，コメントは鉛筆マークのボタンで編集出来ますよ．

**Comment by eeekcct** [comment]
動かす秒数の目標はチームの人と相談して決めるのでまだ決まっていません
