### ISSUE TITLE
masterブランチ Segmentation faultがでる

### ISSUE THREAD

**Issue by ujiuji54** [eeekcct/katenji#3]
573  word_image = TTF_RenderUTF8_Blended(font, "ボタンを押したらSTART", white)    ;
で引っかかる

勝手にリファクタリングは動いた

**Comment by TateIsuKanna** [comment]
フォントが無いからって訳じゃ無いの?

**Comment by TateIsuKanna** [comment]
仮想マシンでしか確認出来て無かったから実機で動いて嬉しい😃

**Comment by ujiuji54** [comment]
フォントファイルは既に追加してる

動いたけど挙動少し変

**Comment by TateIsuKanna** [comment]
そう，下に降りる動作が変．元のは上手く動いてたよね?普通のインベーダーみたいに．

**Comment by ujiuji54** [comment]
下に降りる動作が変だったのと敵の打つ球が無かった(表示されてない？)。

元のやつは動いてた

**Comment by TateIsuKanna** [comment]
勝手にリファクタリング上手く動いてます
